namespace CsFeel;

public enum FeelParserError
{
    INVALID_ARGUMENT,
    INVALID_NUMBER_OF_ARGUMENTS,
    INVALID_FUNCTION_NAME,
    INVALID_OPERAND,
    INVALID_OPERATION,
    INVALID_LEFT_HAND_VALUE,
    INVALID_RIGHT_HAND_VALUE
}