namespace CsFeel;

public enum FeelParserError
{
    UNARY_INVALID_OPERATOR,
    UNARY_INVALID_RIGHT_HAND_VALUE,
    SOME_INVALID_COLLECTION_VALUE,
    SOME_INVALID_PREDICATE_VALUE,
    RANGE_INVALID_TYPE,
    INSTANCEOF_INVALID_TYPE_NAME,
    IN_INVALID_LEFT_HAND_VALE,
    IN_INVALID_RIGHT_HAND_VALE,
    IFTHEN_INVALID_CONDITION_VALUE,
    FOR_INVALID_COLLECTION_VALUE,
    CONTEXT_INVALID_TARGET_VALUE,
    INVALID_NUMBER_OF_ARGUMENTS,
    INVALID_FUNCTION_NAME,
    INVALID_OPERAND,
    INVALID_OPERATION,
    INVALID_EXPRESSION,
    INVALID_TYPE,
}